blank_issues_enabled: false
contact_links:
  - name: OcteDigital Engineering Support
    url: https://github.com/OcteDigital1/.github/blob/main/.github/SUPPORT.md
    about: Please read our support guidelines before opening an issue.
  - name: Report a Security Vulnerability
    url: https://github.com/OcteDigital1/.github/blob/main/.github/SECURITY.md
    about: Please review our security policy for reporting vulnerabilities.
